
set(FFTW3_INSTALL_DIR ${THIRD_PARTY_INSTALL_PATH}/fftw3)
set(FFTW3_INCLUDE_DIR ${FFTW3_INSTALL_DIR}/include)
set(FFTW3_LIBRARY_DIR ${FFTW3_INSTALL_DIR}/lib)

if (ARMEABI_V7A)
    set(FFTW3_LIBRARIE "${FFTW3_INSTALL_DIR}/lib/libfftw3f${CMAKE_STATIC_LIBRARY_SUFFIX}" CACHE FILEPATH "FFTW3_LIBRARIE" FORCE)
    set(FFTW3_THREAD_LIBRARIE "${FFTW3_INSTALL_DIR}/lib/libfftw3f_threads${CMAKE_STATIC_LIBRARY_SUFFIX}" CACHE FILEPATH "FFTW3_THREAD_LIBRARIE" FORCE)
else ()
    set(FFTW3_LIBRARIE "${FFTW3_INSTALL_DIR}/lib/libfftw3${CMAKE_STATIC_LIBRARY_SUFFIX}" CACHE FILEPATH "FFTW3_LIBRARIE" FORCE)
    set(FFTW3_THREAD_LIBRARIE "${FFTW3_INSTALL_DIR}/lib/libfftw3_threads${CMAKE_STATIC_LIBRARY_SUFFIX}" CACHE FILEPATH "FFTW3_THREAD_LIBRARIE" FORCE)
endif ()

if (NOT EXISTS ${FFTW3_INSTALL_DIR} OR (NOT EXISTS ${FFTW3_INCLUDE_DIR}) OR (NOT EXISTS ${FFTW3_LIBRARY_DIR}))
    set(FFTW3_INSTALL FALSE)
else ()
    set(FFTW3_INSTALL TRUE)
endif ()

if (${FFTW3_INSTALL})
    add_library(fftw3 STATIC IMPORTED GLOBAL)
    set_property(TARGET fftw3 PROPERTY IMPORTED_LOCATION ${FFTW3_LIBRARIE})
    set_property(TARGET fftw3 PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${FFTW3_INCLUDE_DIR})

    add_library(fftw3_thread STATIC IMPORTED GLOBAL)
    set_property(TARGET fftw3_thread PROPERTY IMPORTED_LOCATION ${FFTW3_THREAD_LIBRARIE})
    set_property(TARGET fftw3_thread PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${FFTW3_INCLUDE_DIR})

    set(FFTW3_FOUND TRUE)
    include_directories(${FFTW3_INCLUDE_DIR})
else ()
    set(FFTW3_FOUND FALSE)
endif ()