include(FindPackageHandleStandardArgs)

set(CMAKE_FIND_LIBRARY_SUFFIXES_SAV ${CMAKE_FIND_LIBRARY_SUFFIXES})

if (X265_USE_STATIC)
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_STATIC_LIBRARY_SUFFIX})
    set(SHARED_OR_STATIC "STATIC")
else ()
    set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES_SAV})
    set(SHARED_OR_STATIC "SHARED")
endif ()

unset(X265_LIBRARY CACHE)
find_library(
        X265_LIBRARY
        NAMES "x265"
        PATHS ${X265_INSTALL_PATH}
        PATH_SUFFIXES "lib" "lib64"
        NO_DEFAULT_PATH
        NO_CMAKE_FIND_ROOT_PATH
)

unset(X265_INCLUDE CACHE)
find_path(
        X265_INCLUDE_DIR
        NAMES "x265.h"
        PATHS ${X265_INSTALL_PATH}
        PATH_SUFFIXES "include"
        NO_DEFAULT_PATH
        NO_CMAKE_FIND_ROOT_PATH
)

find_package_handle_standard_args(X265 DEFAULT_MSG X265_LIBRARY X265_INCLUDE_DIR)

if (X265_FOUND)
    if (NOT TARGET x265)
        add_library(x265 ${SHARED_OR_STATIC} IMPORTED GLOBAL)
    endif ()
    set_property(TARGET x265 PROPERTY IMPORTED_LOCATION ${X265_LIBRARY})
    include_directories(${X265_INCLUDE_DIR})
    set(X265_INCLUDE_DIRS ${X265_INCLUDE_DIR})
    set(X265_LIBRARIES ${X265_LIBRARY})
endif ()

### restore
set(CMAKE_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES_SAV})
set(SHARED_OR_STATIC)