
set(GFLAGS_INSTALL_DIR ${THIRD_PARTY_INSTALL_PATH}/gflags)
set(GFLAGS_INCLUDE_DIR ${GFLAGS_INSTALL_DIR}/include)
set(GFLAGS_LIBRARY_DIR ${GFLAGS_INSTALL_DIR}/lib)

set(GFLAGS_LIBRARIE "${GFLAGS_INSTALL_DIR}/lib/libgflags${CMAKE_STATIC_LIBRARY_SUFFIX}" CACHE FILEPATH "GFLAGS_LIBRARIES" FORCE)

if (NOT EXISTS ${GFLAGS_INSTALL_DIR} OR (NOT EXISTS ${GFLAGS_INCLUDE_DIR}) OR (NOT EXISTS ${GFLAGS_LIBRARY_DIR}))
    set(GFLAGS_INSTALL FALSE)
else ()
    set(GFLAGS_INSTALL TRUE)
endif ()

if (${GFLAGS_INSTALL})
    add_library(gflags STATIC IMPORTED GLOBAL)
    set_property(TARGET gflags PROPERTY IMPORTED_LOCATION ${GFLAGS_LIBRARIE})
    set_property(TARGET gflags PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${GFLAGS_INCLUDE_DIR})
    set(GFlags_FOUND TRUE)
    include_directories(${GFLAGS_INCLUDE_DIR})
else ()
    set(GFlags_FOUND FALSE)
endif ()