
### compiler version info
message(STATUS "CXX compiler: ${CMAKE_CXX_COMPILER}, version: "
        "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "C compiler: ${CMAKE_C_COMPILER}, version: "
        "${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION}")

### enable fpic
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

### lib and bin path
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)
set(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/lib)

### third party
if (NOT THIRD_PARTY_INDEPENDENT_INSTALL)
    set(THIRD_PARTY_INDEPENDENT_INSTALL FALSE)
else()
    set(THIRD_PARTY_INDEPENDENT_INSTALL TRUE)
endif()


if (NOT THIRD_PARTY_PATH)
    set(THIRD_PARTY_PATH ${CMAKE_BINARY_DIR}/third_party)
endif()

if (NOT THIRD_PARTY_INSTALL_PATH)
    set(THIRD_PARTY_INSTALL_PATH ${THIRD_PARTY_PATH}/install/${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR})
endif()

### cpu count
include(ProcessorCount)
ProcessorCount(CPU_COUNT)

set(THIRD_PARTY_BUILD_TYPE Release)

message(STATUS "CMAKE_MODULE_PATH: ${CMAKE_MODULE_PATH}")
message(STATUS "THIRD_PARTY_INSTALL_PATH: ${THIRD_PARTY_INSTALL_PATH}")

### ndk config
if (ANDROID)
    include(${CMAKE_CURRENT_LIST_DIR}/android.cmake)	
endif()
